#!/bin/bash 
blih -u hugo.liegard@epitech.eu repository create $1
blih -u hugo.liegard@epitech.eu repository setacl $1 ramassage-tek r
blih -u hugo.liegard@epitech.eu repository getacl $1
git clone git@git.epitech.eu:/hugo.liegard@epitech.eu/$1

 
